spring.application.name=sistema-votacao

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_votacao
spring.datasource.username=postgres
spring.datasource.password=mi#231025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=VG90YWxseVJhbmRvbVNlY3JldEtleUZvclZvdGFjYW9TeXN0ZW0yMDI2
app.jwt.issuer=sistema-votacao
app.jwt.admin-expiration-hours=8

app.admin.email=admin@votacao.local
app.admin.password=Admin@123456